# Generated by Django 3.0.5 on 2020-12-29 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventolembret',
            name='UserLembrete',
        ),
        migrations.AddField(
            model_name='eventolembret',
            name='UserLembrete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
