# Generated by Django 3.0.5 on 2021-06-20 11:53

import alojamento.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('Type_Alojamento', models.CharField(choices=[('Hotel', 'Hotel'), ('Apart-hotel', 'Apart-hotel'), ('Residencial', 'Residencial'), ('Pensão', 'Pensão'), ('Lodge', 'Lodge'), ('Resort', 'Resort'), ('Outros', 'Outros')], max_length=20)),
                ('Estrela', models.IntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, ' 5 estrelas')])),
                ('Aprovado', models.BooleanField(default=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('pais', models.CharField(max_length=50)),
                ('Provincia', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=50)),
                ('linha', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to=alojamento.models.uploud_image)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('whatsApp', models.CharField(blank=True, max_length=15, null=True)),
                ('LinkedIn', models.CharField(blank=True, max_length=254, null=True)),
                ('rec_in', models.TimeField()),
                ('rec_out', models.TimeField()),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alojamento.Alojamento')),
            ],
        ),
        migrations.CreateModel(
            name='AlojamentoViewsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_view_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('data_view', models.DateField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamento.Alojamento')),
            ],
        ),
    ]
