# Generated by Django 3.0.5 on 2021-02-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('whatsApp', models.CharField(blank=True, max_length=15, null=True)),
                ('LinkedIn', models.CharField(blank=True, max_length=254, null=True)),
                ('rec_in', models.TimeField()),
                ('rec_out', models.TimeField()),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alojamento.Alojamento')),
            ],
        ),
    ]
