# Generated by Django 3.0.5 on 2021-03-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamento', '0002_contactsschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamento',
            name='Type_Alojamento',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Apart-hotel', 'Apart-hotel'), ('Residencial', 'Residencial'), ('Pensão', 'Pensão'), ('Lodge', 'Lodge'), ('Resort', 'Resort'), ('Outros', 'Outros')], max_length=20),
        ),
    ]
