# Generated by Django 3.0.5 on 2021-06-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alojamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_quarto', models.CharField(choices=[('Quarto Solteiro', 'Quarto Solteiro'), ('Quarto Duplo', 'Quarto Duplo'), ('Quarto Casal', 'Quarto Casal'), ('Outros', 'Outros')], max_length=20)),
                ('Caract', models.CharField(choices=[('Standard', 'Standard'), ('Master', 'Master'), ('Delux', 'Delux'), ('Outros', 'Outros')], max_length=20)),
                ('percentagem', models.FloatField()),
                ('data', models.DateField(auto_now_add=True)),
                ('init_data', models.DateField(blank=True, null=True)),
                ('valid_data', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamento.Alojamento')),
            ],
        ),
    ]
