# Generated by Django 3.0.5 on 2021-02-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
        ('promocoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='quartos_em_prom',
        ),
        migrations.AddField(
            model_name='promocao',
            name='quarto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quartos.Quarto'),
            preserve_default=False,
        ),
    ]
