# Generated by Django 3.0.5 on 2021-02-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0002_auto_20210205_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='quarto',
        ),
        migrations.AddField(
            model_name='promocao',
            name='Caract',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Master', 'Master'), ('Delux', 'Delux'), ('Outros', 'Outros')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocao',
            name='tipo_quarto',
            field=models.CharField(choices=[('Quarto Solteiro', 'Quarto Solteiro'), ('Quarto Duplo', 'Quarto Duplo'), ('Quarto Casal', 'Quarto Casal'), ('Outros', 'Outros')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
