# Generated by Django 3.0.5 on 2021-02-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0003_auto_20210205_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocao',
            old_name='new_preco',
            new_name='percentagem',
        ),
    ]
