# Generated by Django 3.0.5 on 2021-06-20 11:53

import ImagensPerfil.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=ImagensPerfil.models.uploud_image)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.Quarto')),
            ],
        ),
    ]
