# Generated by Django 3.0.5 on 2021-06-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0002_auto_20210205_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='Status',
            field=models.CharField(choices=[('Ocupado', 'Ocupado'), ('Disponivel', 'Disponivel'), ('Outros', 'Outros')], default='Disponivel', max_length=10),
        ),
    ]
