# Generated by Django 3.0.5 on 2021-02-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguir', '0002_auto_20210204_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguir',
            old_name='hotel_id',
            new_name='HOTEL',
        ),
        migrations.RenameField(
            model_name='seguir',
            old_name='User_id',
            new_name='USER',
        ),
    ]
