# Generated by Django 3.0.5 on 2021-02-04 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seguir', '0003_auto_20210204_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguir',
            old_name='HOTEL',
            new_name='hotel_id',
        ),
        migrations.RemoveField(
            model_name='seguir',
            name='USER',
        ),
        migrations.AddField(
            model_name='seguir',
            name='User_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
